## You should change each of the following fields
## to customize your blog

title: "MaryEllen's Super Stat 386 Blog"
description: "I will be creating and adding posts to this blog throughout my Winter 2025 semester at BYU! I am excited to share what I am learning." 
author: MaryEllen Faulconer
author_description: "I am a third-year student at BYU Provo, studying Data Science. I love all things sports and hope to one day work front office operations for one of my favorite sports teams! I am also super interested in player development!" 

url: https://mfaulconer.github.io
baseurl: Stat386-Blog ## change this to the name of your blog repository
header_image: /assets/img/headerimg.jpg ## change your header image if you want

## Add your social media user names.  Github is required, the rest are optional
social:
    github:  mfaulconer
    twitter: 
    facebook: mfaulconer_
    email: faulconer.maryellen@gmail.com
    linkedin: maryellen-faulconer-datascience
    youtube: 
    tumblr: 
    website: 



### Advanced Settings (don't change below unless you know what you are doing)

paginate_path: "blog/page:num/"
permalink: blog/:title/

# Header Option
# header: large

sass:
    style: compressed

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

navigation:
    - title: Home
      url: /index.html
    - title: About
      url: /about




